---
name: 'Code Composer Studio Project Builder - CGT v21.6.0'
description: 'GitHub action to build a Code Composer Studio Project'
author: 'Grahame White'
inputs:
  project-path:
    description: 'Path to the project files'
    required: true
    default: './'
  project-name:
    description: 'Name of the CCS project to be built'
    required: true
  build-configuration:
    description: 'The build configuration to use when building'
    required: false
    default: 'Debug'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/apollo-fire/ccs-build:21.6.0-abc-63-enable-release-firmware-build'
  # image: 'docker://ghcr.io/apollo-fire/ccs-build:21.6.0-v0.0.5'
  args:
    - ${{ inputs.project-path }}
    - ${{ inputs.project-name }}
    - ${{ inputs.build-configuration }}
branding:
  icon: 'code'
  colour: 'red'
