---
name: 'Code Composer Studio Project Builder - CGT v18.1.3'
description: 'GitHub action to build a Code Composer Studio Project'
author: 'Grahame White'
inputs:
  project-path:
    description: 'Path to the project files'
    required: true
    default: './'
  build-configuration:
    description: 'The build configuration to use when building'
    required: false
    default: 'Debug'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/apollo-fire/ccs-build:18.1.3-v0.0.5'
  args:
    - ${{ inputs.project-path }}
    - ${{ inputs.build-configuration }}
branding:
  icon: 'code'
  colour: 'red'
