---
name: create ccs_build container - dry run

on:
  workflow_dispatch:
  merge_group:

  pull_request:
    types: [opened, synchronize, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/_build_docker_images.yml
    with:
      push: false
    secrets: inherit
