---
name: create ccs_build container

on:
  release:
    types: [published]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/_build_docker_images.yml
    with:
      push: true
    secrets: inherit
